# src/docker-compose.yml

version: "3.3"

services:
  # prometheus:
  #   image: "docker.io/prometheus"
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - prometheus_data:/prometheus
  #   networks:
  #     - back_net
  #     - front_net

  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   user: root
  #   networks:
  #     - back_net
  #     - front_net
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  post_db:
    image: "mongo:5.0"
    volumes:
     - ./post_db:/data/db
    networks:
     - back_net

  ui:
    image: "${USER_NAME}/ui:${UI_VERSION}"
    ports:
     - ${UI_PORT}:9292/tcp
    networks:
     - front_net
    logging:
    driver: "fluentd"
    options:
      fluentd-address: localhost:24224
      tag: service.ui

  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
     - front_net
     - back_net

  comment:
    image: "${USER_NAME}/comment:${COMMENT_VERSION}"
    networks:
     - front_net
     - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
