---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
      - image: virtualb0xloame/post:logging
        name: post
      env:
        - name: POST_DATABASE_HOST
          value: post_db
