version: '3.3'
services:
  post_db:
    volumes:
      - post_db:/data/db
  ui:
    volumes:
      - ui_app:/app
    command: [ "puma", "--debug", "-w", "2" ]
    ports:
      - 9292:9292/tcp
  post:
    volumes:
      - post_app:/app
  comment:
    volumes:
      - comment_app:/app
    command: [ "puma", "--debug", "-w", "2" ]
volumes:
  post_db:
    name: post_db
  ui_app:
    name: ui_app
  comment_app:
    name: comment_app
  post_app:
    name: post_app
