version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    env_file: .env
    build: ./post-py
    image: ${USERNAME}/post:${P_VER}
    networks:
      - back_net
      - front_net

  comment:
    env_file: .env
    build: ./comment
    image: ${USERNAME}/comment:${C_VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  reddit:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24

  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
